#optional, only to override user/pass
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    #h2 data is lost after app restart, we can avoid that by writing data to file using url
    #url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      #path: /h2
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: embedded
      #we can set about to never and spring boot will not initialize in memory database on startup

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


